### ISSUE TITLE
[Documentation] Channel layer configuration is different from Channels official docs

### ISSUE THREAD

**Issue by nicocesar** [xavierlesa/channels-asgi-mqtt#1]
I'm new to Channels, and following this tutorial I see: 

https://channels.readthedocs.io/en/latest/topics/channel_layers.html#configuration

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis-server-name", 6379)],
        },
    },
}
```

channels-asgi-mqtt documentation[1] doesn't explicitly mentions this as part of the setup. Is this something expected? or is this not in the scope of the project?

[1] https://github.com/xavierlesa/channels-asgi-mqtt#configuration

**Comment by xavierlesa** [comment]
Yes this is expected because you can't use `channels-asgi-mqtt` whitout configure your layer correctly.

As mentioned in configuration:

> First you would to configure a valid `channel_layer` endpoint to consume and connect between chasgimqtt and channels.
